### ISSUE TITLE
PlanetWren Issues

### ISSUE THREAD

**Issue by Causeless** [TheOpenSpaceProgram/urho-osp#7]
Malformed triangles, resulting in edges going through the centre of the sphere:
![capturesphere](https://user-images.githubusercontent.com/172739/46585763-d72b0680-ca6c-11e8-87c3-4b3a6d19e28c.PNG)

```
SubTriangle* children = get_triangle(tri->m_children);

set_neighbors(children[0], tri->m_children + 3, tri->m_neighbors[1], tri->m_neighbors[2]);
set_neighbors(children[1], tri->m_neighbors[0], tri->m_children + 3, tri->m_neighbors[2]);
set_neighbors(children[2], tri->m_neighbors[0], tri->m_neighbors[1], tri->m_children + 3);
set_neighbors(children[3], tri->m_children + 0, tri->m_children + 1, tri->m_children + 2);
```

This code uses children[1] - [3] without checking that they exist, meaning it writes beyond the end of the triangles array. `tri->m_children + 3`  is inconsistent: why are m_neighbors using array indexing and m_children using pointer arithmetic? It'd make more sense if these all use [], i.e `tri->m_children[3]`.

```
inline uint8_t PlanetWrenderer::neighboor_index(SubTriangle& tri, trindex lookingFor)
{
    if (tri.m_neighbors[0] == lookingFor)
        return 0;
    else if (tri.m_neighbors[1] == lookingFor)
        return 1;
    else if (tri.m_neighbors[2] == lookingFor)
        return 2;
    // this means there's an error
    //printf("Errrrorr \n");
    return 255;
}
```

A loop would be a little cleaner here (and should be unrolled by the compiler anyways), but that aside, why return 255? This should be an assert.

**Comment by Causeless** [comment]
Also forgot to mention - should be "neighbour" (British English) or "neighbor" (American English), not "neighboor".

**Comment by Capital-Asterisk** [comment]
This should be fixed by now.
